In [1]:
import sys
import matplotlib.pyplot as plt
import numpy as np
import csv

In [2]:
def load_data(file_name):
	lines = list()
	dataset = list()
	# Open file
	with open(file_name, 'rt') as f:
		reader = csv.reader(f, delimiter=',')
		# Save each row in list lines
		for row in reader:
			if (row != []):
				lines.append(row)
	# Iterate the list
	for line in lines:
		d = list()
		# Append the data to the list d
		for item in line[0:len(line)-1]:
			d.append(float(item))
		d.append(0*(line[len(line)-1]=='Iris-setosa') +
				1*(line[len(line)-1]=='Iris-versicolor') +
				2*(line[len(line)-1]=='Iris-virginica'))
		# Otherwise append the 0 or 1 of the pima dataset

		dataset.append(d)
	# Return the results as 2 different arrays. The first is the data and the second are the classes.
	return np.array(dataset)[:,0:len(dataset[0])-1], np.array(dataset)[:,len(dataset[0])-1]

In [3]:
def f(x, w):
	return 1 if np.dot(w,x)>0 else -1

In [4]:
def f(x, w):
	return 1 if np.dot(w,x)>0 else -1

iris = ["Iris-setosa", "Iris-versicolor", "Iris-virginica"]
max_iter = 1000
for c in range(0, 3):
	iris_data, iris_labels = load_data('UCIdata-exercise1/iris.data')
	for j in range(len(iris_data)):
		if iris_labels[j] == c :
			iris_labels[j] = 1.0
		else:
			iris_labels[j] = -1.0
	data = np.column_stack([iris_labels, iris_data])

	# Initialize Workspace
	patterns = np.empty([len(data), 4])
	dw = np.zeros([4,])
	update_needed = np.empty([len(data), 1])
	inner_product = np.zeros([len(data), 1])

	# Copy data to our arrays
	target = data[:,0] # Class
	initial_patterns = data[:,1:5] # Patterns
	for i in range(0,150):
		patterns[i] = target[i]*initial_patterns[i,:] #Class*Pattern
	weights = np.zeros([4,])
	finished = False
	iterations = 0

	# Run the algorithm
	while(not(finished) and iterations<=max_iter):
		iterations += 1
		for i in range(0,150):
			inner_product[i] = np.dot(weights.reshape(4,),patterns[i,:])
			if(inner_product[i]<=0):
				update_needed[i]=1
				dw = patterns[i,:]
			else:
				update_needed[i]=0
				dw = np.zeros([4,])
			weights += dw
		finished = sum(update_needed)==0

	# Show results
	print(weights)
	if(iterations > max_iter):
		print(iris[c], 'is not linearly seperable')
	else:
		errors = 0
		for i in range(0, len(data)):
			if (f(initial_patterns[i,:], weights) != target[i]):
				errors += 1
		print(errors,' errors for ', iris[c])

[ 1.3  4.1 -5.2 -2.2]
0  errors for  Iris-setosa
[  40.9  -56.6   14.6 -139.8]
Iris-versicolor is not linearly seperable
[-145.  -147.6  186.7  256.9]
Iris-virginica is not linearly seperable
